server:
  port: 8081
spring:
  application:
    name: dubbo-provider-demo
dubbo:
  scan:
    base-packages: com.strr.demo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181